version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: python3 /app/run.py
    environment:
      - MONGODB_HOST=mongodb://db:27017/functree?tz_aware=true

  db:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    command: mongod

volumes:
  mongo_data:
